# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5f1483ab9565ded0401270cfc3ac6c23d733cfe417bb9b93ae6ddcc3a316c6f95c25c19a34dc309b877e03fc71be8da5557a5ffa470b9282de53d83f1fb052e

test:
  secret_key_base: 34a9a587da3ceff82570023a29baa0f14a3ff493134ab052e6c5bc69810fbd4d8f0ec8f15a6045ef001d1c0e36ac8fe9a83dd38701275c0763b460d1fe1c5875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
